// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "LabelValue_GUI.h"
#include "LabelValue_Controller.h"

void LabelValue_GUI::cb_input_i(Fl_Input_Choice* o, void* v) {
  controller->cb_input (o, v);
}
void LabelValue_GUI::cb_input(Fl_Input_Choice* o, void* v) {
  ((LabelValue_GUI*)(o->parent()->parent()->user_data()))->cb_input_i(o,v);
}

Fl_Menu_Item LabelValue_GUI::menu_choice[] = {
 {"V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

LabelValue_GUI::LabelValue_GUI() {
  { window = new Fl_Double_Window(480, 260, "LabelValue");
    window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(0, 0, 480, 260);
      { input = new Fl_Input_Choice(49, 70, 120, 30, "Input");
        input->callback((Fl_Callback*)cb_input);
        input->align(Fl_Align(FL_ALIGN_TOP));
        input->when (FL_WHEN_ENTER_KEY | FL_WHEN_RELEASE);
        input->input ()->when (FL_WHEN_ENTER_KEY | FL_WHEN_RELEASE);
      } // Fl_Input_Choice* input
      { choice = new Fl_Choice(49, 151, 120, 30, "Parse as");
        choice->down_box(FL_BORDER_BOX);
        choice->align(Fl_Align(FL_ALIGN_TOP));
        choice->menu(menu_choice);
      } // Fl_Choice* choice
      { output = new Fl_Output(292, 69, 120, 30, "Output");
        output->align(Fl_Align(FL_ALIGN_TOP));
      } // Fl_Output* output
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
}
