// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LabelValue_GUI_h
#define LabelValue_GUI_h
#include <FL/Fl.H>
class LabelValue_Controller;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Output.H>

class LabelValue_GUI {
public:
  LabelValue_Controller* controller; 
  LabelValue_GUI();
  Fl_Double_Window *window;
  Fl_Input_Choice *input;
private:
  inline void cb_input_i(Fl_Input_Choice*, void*);
  static void cb_input(Fl_Input_Choice*, void*);
public:
  Fl_Choice *choice;
  static Fl_Menu_Item menu_choice[];
  Fl_Output *output;
};
#endif
