// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABChecker_GUI_h
#define LABChecker_GUI_h
#include <FL/Fl.H>
class LABChecker_Controller;
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
#include "LABChecker_GUI_Digital_Input_Table.h"

class LABChecker_GUI {
public:
  LABChecker_Controller* m_LABChecker_Controller; 
  LABChecker_GUI();
  Fl_Double_Window *main_fl_window;
  static Fl_Menu_Item menu_[];
  Fl_Input_Choice *simple_dc_fl_input_choice_dc_output;
  Fl_Input_Choice *simple_dc_fl_input_choice_dc_input;
  Fl_Input_Choice *simple_dc_fl_input_choice_samples;
  Fl_Input_Choice *simple_dc_fl_input_choice_sampling_rate;
  Fl_Input_Choice *simple_dc_fl_input_choice_base;
  Fl_Button *simple_dc_fl_button_create_file;
  Fl_Choice *digital_fl_choice_input_bits;
private:
  inline void cb_digital_fl_choice_input_bits_i(Fl_Choice*, void*);
  static void cb_digital_fl_choice_input_bits(Fl_Choice*, void*);
  static Fl_Menu_Item menu_digital_fl_choice_input_bits[];
public:
  Fl_Choice *digital_fl_choice_output_bits;
private:
  inline void cb_digital_fl_choice_output_bits_i(Fl_Choice*, void*);
  static void cb_digital_fl_choice_output_bits(Fl_Choice*, void*);
  static Fl_Menu_Item menu_digital_fl_choice_output_bits[];
public:
  Fl_Input *digital_fl_input_output_count;
private:
  inline void cb_digital_fl_input_output_count_i(Fl_Input*, void*);
  static void cb_digital_fl_input_output_count(Fl_Input*, void*);
public:
  Fl_Button *digital_fl_button_create_file;
private:
  inline void cb_digital_fl_button_create_file_i(Fl_Button*, void*);
  static void cb_digital_fl_button_create_file(Fl_Button*, void*);
public:
  LABChecker_GUI_Digital_Input_Table *digital_labchecker_gui_digital_input_table_table;
};
#endif
