// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABChecker_GUI_h
#define LABChecker_GUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_fl_window;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice *simple_dc_fl_input_choice_dc_output;
extern Fl_Input_Choice *simple_dc_fl_input_choice_dc_input;
extern Fl_Input_Choice *simple_dc_fl_input_choice_samples;
extern Fl_Input_Choice *simple_dc_fl_input_choice_sampling_rate;
extern Fl_Input_Choice *simple_dc_fl_input_choice_base;
#include <FL/Fl_Button.H>
extern Fl_Button *simple_dc_fl_button_create_file;
#include <FL/Fl_Choice.H>
extern Fl_Button *simple_dc_fl_button_create_file;
extern Fl_Menu_Item menu_[];
extern Fl_Menu_Item menu_Bits[];
#endif
