// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABChecker_h
#define LABChecker_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Group *simple_wizard_fl_group_output;
#include <FL/Fl_Choice.H>
extern Fl_Choice *simple_wizard_fl_input_choice_output_type;
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice *simple_wizard_fl_input_choice_output_amplitude;
extern Fl_Input_Choice *simple_wizard_fl_input_choice_output_frequency;
extern Fl_Input_Choice *simple_wizard_fl_input_choice_output_duration;
extern Fl_Group *simple_wizard_fl_group_input;
extern Fl_Choice *simple_wizard_fl_choice_input_type;
extern Fl_Input_Choice *simple_wizard_fl_input_choice_input_amplitude;
extern Fl_Input_Choice *simple_wizard_fl_input_choice_input_frequency;
extern Fl_Input_Choice *simple_wizard_fl_input_choice_input_duration;
#include <FL/Fl_Button.H>
extern Fl_Button *simple_wizard_fl_button_generate;
extern Fl_Menu_Item menu_[];
extern Fl_Menu_Item menu_simple_wizard_fl_input_choice_output_type[];
extern Fl_Menu_Item menu_simple_wizard_fl_choice_input_type[];
#endif
