// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "LABSoft_GUI.h"
#include "LABSoft_Controller.h"

void LABSoft_GUI::cb_oscilloscope_fl_light_button_run_stop_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Oscilloscope.cb_run_stop (o, v);
}
void LABSoft_GUI::cb_oscilloscope_fl_light_button_run_stop(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_light_button_run_stop_i(o,v);
}

void LABSoft_GUI::cb_oscilloscope_fl_button_single_i(Fl_Button* o, void* v) {
  m_LABSoft_Controller->m_Oscilloscope.cb_single (o, v);
}
void LABSoft_GUI::cb_oscilloscope_fl_button_single(Fl_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_button_single_i(o,v);
}

void LABSoft_GUI::cb_oscilloscope_fl_light_button_channel_1_enable_i(Fl_Light_Button* o, void*) {
  m_LABSoft_Controller->m_Oscilloscope.cb_channel_enable_disable (o, (void*)0);
}
void LABSoft_GUI::cb_oscilloscope_fl_light_button_channel_1_enable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_light_button_channel_1_enable_i(o,v);
}

void LABSoft_GUI::cb_oscilloscope_fl_input_choice_channel_1_volts_per_division_i(Fl_Input_Choice* o, void*) {
  m_LABSoft_Controller->m_Oscilloscope.cb_volts_per_division (o, (void*)0);
}
void LABSoft_GUI::cb_oscilloscope_fl_input_choice_channel_1_volts_per_division(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_input_choice_channel_1_volts_per_division_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_channel_1_volts_per_division[] = {
 {"50 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_channel_1_vertical_offset[] = {
 {"25 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-25 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_oscilloscope_fl_light_button_channel_2_enable_i(Fl_Light_Button* o, void*) {
  m_LABSoft_Controller->m_Oscilloscope.cb_channel_enable_disable (o, (void*)1);
}
void LABSoft_GUI::cb_oscilloscope_fl_light_button_channel_2_enable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_light_button_channel_2_enable_i(o,v);
}

void LABSoft_GUI::cb_oscilloscope_fl_input_choice_channel_2_volts_per_division_i(Fl_Input_Choice* o, void*) {
  m_LABSoft_Controller->m_Oscilloscope.cb_volts_per_division (o, (void*)1);
}
void LABSoft_GUI::cb_oscilloscope_fl_input_choice_channel_2_volts_per_division(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_input_choice_channel_2_volts_per_division_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_channel_2_volts_per_division[] = {
 {"50 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 uV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_channel_2_vertical_offset[] = {
 {"25 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-10 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-20 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-50 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-100 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-200 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-500 mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-10 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-25 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_oscilloscope_fl_input_choice_time_per_division_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Oscilloscope.cb_time_per_division (o, v);
}
void LABSoft_GUI::cb_oscilloscope_fl_input_choice_time_per_division(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_input_choice_time_per_division_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_time_per_division[] = {
 {"50 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_oscilloscope_fl_input_choice_horizontal_offset_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Oscilloscope.cb_x_offset (o, v);
}
void LABSoft_GUI::cb_oscilloscope_fl_input_choice_horizontal_offset(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_oscilloscope_fl_input_choice_horizontal_offset_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_horizontal_offset[] = {
 {"50 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 ns", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_oscilloscope_fl_input_choice_display_mode[] = {
 {"Repeated", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Shift", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Screen", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_voltmeter_fl_choice_unit_i(Fl_Choice* o, void* v) {
  m_LABSoft_Controller->m_Voltmeter.cb_unit (o, v);
}
void LABSoft_GUI::cb_voltmeter_fl_choice_unit(Fl_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_voltmeter_fl_choice_unit_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_voltmeter_fl_choice_unit[] = {
 {"V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {"mV", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_voltmeter_fl_light_button_run_stop_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Voltmeter.cb_run_stop (o, v);
}
void LABSoft_GUI::cb_voltmeter_fl_light_button_run_stop(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_voltmeter_fl_light_button_run_stop_i(o,v);
}

void LABSoft_GUI::cb_voltmeter_fl_light_button_generate_random_values_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Voltmeter.cb_generate_random_values (o, v);
}
void LABSoft_GUI::cb_voltmeter_fl_light_button_generate_random_values(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_voltmeter_fl_light_button_generate_random_values_i(o,v);
}

void LABSoft_GUI::cb_ammeter_fl_choice_unit_i(Fl_Choice* o, void* v) {
  m_LABSoft_Controller->m_Ammeter.cb_unit (o, v);
}
void LABSoft_GUI::cb_ammeter_fl_choice_unit(Fl_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ammeter_fl_choice_unit_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_ammeter_fl_choice_unit[] = {
 {"A", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {"mA", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_ammeter_fl_light_button_run_stop_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Ammeter.cb_run_stop (o, v);
}
void LABSoft_GUI::cb_ammeter_fl_light_button_run_stop(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ammeter_fl_light_button_run_stop_i(o,v);
}

void LABSoft_GUI::cb_ammeter_fl_light_button_generate_random_values_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Ammeter.cb_generate_random_values (o, v);
}
void LABSoft_GUI::cb_ammeter_fl_light_button_generate_random_values(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ammeter_fl_light_button_generate_random_values_i(o,v);
}

void LABSoft_GUI::cb_ohmmeter_fl_choice_unit_i(Fl_Choice* o, void* v) {
  m_LABSoft_Controller->m_Ohmmeter.cb_unit (o, v);
}
void LABSoft_GUI::cb_ohmmeter_fl_choice_unit(Fl_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ohmmeter_fl_choice_unit_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_ohmmeter_fl_choice_unit[] = {
 {"M\316\251", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {"k\316\251", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {"\316\251", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {"m\316\251", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 72, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_ohmmeter_fl_light_button_run_stop_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Ohmmeter.cb_run_stop (o, v);
}
void LABSoft_GUI::cb_ohmmeter_fl_light_button_run_stop(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ohmmeter_fl_light_button_run_stop_i(o,v);
}

void LABSoft_GUI::cb_ohmmeter_fl_light_button_generate_random_values_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Ohmmeter.cb_generate_random_values (o, v);
}
void LABSoft_GUI::cb_ohmmeter_fl_light_button_generate_random_values(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_ohmmeter_fl_light_button_generate_random_values_i(o,v);
}

void LABSoft_GUI::cb_function_generator_fl_light_button_run_stop_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_run_stop (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_light_button_run_stop(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_light_button_run_stop_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_horizontal_position[] = {
 {"5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_time_per_division[] = {
 {"50 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ms/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 us/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 us/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 us/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_vertical_offset[] = {
 {"5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_volts_per_division[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_wave_type_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_wave_type (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_wave_type(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_wave_type_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_wave_type[] = {
 {"Sine", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Square", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Triangle", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"DC", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_frequency_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_frequency (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_frequency(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_frequency_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_frequency[] = {
 {"1 MHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 kHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 Hz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mHz", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_period_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_period (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_period(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_period_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_period[] = {
 {"5 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 s", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"50 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"20 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"10 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"5 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 ms", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 us", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_amplitude_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_amplitude (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_amplitude(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_amplitude_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_amplitude[] = {
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_y_offset_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_y_offset (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_y_offset(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_y_offset_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_y_offset[] = {
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_duty_cycle_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_duty_cycle (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_duty_cycle(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_duty_cycle_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_duty_cycle[] = {
 {"5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-1 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-2 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-3 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-4 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-5 V", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_function_generator_fl_input_choice_phase_i(Fl_Input_Choice* o, void* v) {
  m_LABSoft_Controller->m_Function_Generator.cb_phase (o, v);
}
void LABSoft_GUI::cb_function_generator_fl_input_choice_phase(Fl_Input_Choice* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_function_generator_fl_input_choice_phase_i(o,v);
}

Fl_Menu_Item LABSoft_GUI::menu_function_generator_fl_input_choice_phase[] = {
 {"-360 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-180 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-90 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-45 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"-30 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+30 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+45 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+60 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+90 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+180 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"+360 deg", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_logic_analyzer_fl_input_choice_memory_depth[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_logic_analyzer_fl_input_choice_sample_rate[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_logic_analyzer_fl_input_choice_samples_per_division[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_logic_analyzer_fl_input_choice_time_per_division[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item LABSoft_GUI::menu_logic_analyzer_fl_input_choice_x_offset[] = {
 {"5 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"2 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 V/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"500 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"200 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"100 mV/div", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void LABSoft_GUI::cb_power_supply_fl_light_button_positive_12_volts_enable_disable_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Power_Supply.cb_fl_light_button_run_stop_power_channel (o, v);
}
void LABSoft_GUI::cb_power_supply_fl_light_button_positive_12_volts_enable_disable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_power_supply_fl_light_button_positive_12_volts_enable_disable_i(o,v);
}

void LABSoft_GUI::cb_power_supply_fl_light_button_negative_12_volts_enable_disable_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Power_Supply.cb_fl_light_button_run_stop_power_channel (o, v);
}
void LABSoft_GUI::cb_power_supply_fl_light_button_negative_12_volts_enable_disable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_power_supply_fl_light_button_negative_12_volts_enable_disable_i(o,v);
}

void LABSoft_GUI::cb_power_supply_fl_light_button_positive_5_volts_enable_disable_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Power_Supply.cb_fl_light_button_run_stop_power_channel (o, v);
}
void LABSoft_GUI::cb_power_supply_fl_light_button_positive_5_volts_enable_disable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_power_supply_fl_light_button_positive_5_volts_enable_disable_i(o,v);
}

void LABSoft_GUI::cb_power_supply_fl_light_button_master_enable_disable_i(Fl_Light_Button* o, void* v) {
  m_LABSoft_Controller->m_Power_Supply.cb_fl_light_button_master_run_stop (o, v);
}
void LABSoft_GUI::cb_power_supply_fl_light_button_master_enable_disable(Fl_Light_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_power_supply_fl_light_button_master_enable_disable_i(o,v);
}

void LABSoft_GUI::cb_circuit_checker_fl_button_choose_circuit_checker_file_i(Fl_Button* o, void* v) {
  m_LABSoft_Controller->m_Circuit_Checker.cb_fl_button_choose_circuit_checker_file (o, v);
}
void LABSoft_GUI::cb_circuit_checker_fl_button_choose_circuit_checker_file(Fl_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_circuit_checker_fl_button_choose_circuit_checker_file_i(o,v);
}

void LABSoft_GUI::cb_circuit_checker_fl_button_start_circuit_checking_i(Fl_Button* o, void* v) {
  m_LABSoft_Controller->m_Circuit_Checker.cb_fl_button_start_circuit_checking (o, v);
}
void LABSoft_GUI::cb_circuit_checker_fl_button_start_circuit_checking(Fl_Button* o, void* v) {
  ((LABSoft_GUI*)(o->parent()->parent()->parent()->user_data()))->cb_circuit_checker_fl_button_start_circuit_checking_i(o,v);
}

LABSoft_GUI::LABSoft_GUI() {
  printf("DEBUG: LABSoft_GUI Start\n");
  { main_fl_window = new Fl_Double_Window(1365, 765, "LABSoft v0.1a");
    main_fl_window->user_data((void*)(this));
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 1366, 768);
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Home");
        o->hide();
        { Fl_Box* o = new Fl_Box(0, 0, 1366, 768, "LABSoft v1.0");
          o->labelsize(60);
          o->labelcolor((Fl_Color)46);
        } // Fl_Box* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Oscilloscope");
        { oscilloscope_fl_light_button_run_stop = new Fl_Light_Button(1205, 80, 120, 60, "Run");
          oscilloscope_fl_light_button_run_stop->callback((Fl_Callback*)cb_oscilloscope_fl_light_button_run_stop);
          oscilloscope_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* oscilloscope_fl_light_button_run_stop
        { oscilloscope_fl_button_single = new Fl_Button(1205, 160, 120, 60, "Single");
          oscilloscope_fl_button_single->callback((Fl_Callback*)cb_oscilloscope_fl_button_single);
        } // Fl_Button* oscilloscope_fl_button_single
        { oscilloscope_labsoft_oscilloscope_display_group_display = new LABSoft_Oscilloscope_Display_Group(24, 60, 800, 660);
          oscilloscope_labsoft_oscilloscope_display_group_display->box(FL_FLAT_BOX);
          oscilloscope_labsoft_oscilloscope_display_group_display->color(FL_FOREGROUND_COLOR);
          oscilloscope_labsoft_oscilloscope_display_group_display->selection_color(FL_BACKGROUND_COLOR);
          oscilloscope_labsoft_oscilloscope_display_group_display->labeltype(FL_NORMAL_LABEL);
          oscilloscope_labsoft_oscilloscope_display_group_display->labelfont(0);
          oscilloscope_labsoft_oscilloscope_display_group_display->labelsize(14);
          oscilloscope_labsoft_oscilloscope_display_group_display->labelcolor(FL_FOREGROUND_COLOR);
          oscilloscope_labsoft_oscilloscope_display_group_display->align(Fl_Align(FL_ALIGN_TOP));
          oscilloscope_labsoft_oscilloscope_display_group_display->when(FL_WHEN_RELEASE);
          { Fl_Box* o = new Fl_Box(69, 125, 720, 540);
            o->box(FL_FLAT_BOX);
            o->color((Fl_Color)79);
            o->selection_color(FL_YELLOW);
            o->hide();
            o->deactivate();
          } // Fl_Box* o
          oscilloscope_labsoft_oscilloscope_display_group_display->end();
        } // LABSoft_Oscilloscope_Display_Group* oscilloscope_labsoft_oscilloscope_display_group_display
        { oscilloscope_fl_group_vertical_channel_1 = new Fl_Group(0, 0, 1366, 768);
          { Fl_Box* o = new Fl_Box(845, 95, 160, 240, "Channel 1");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { oscilloscope_fl_light_button_channel_1_enable = new Fl_Light_Button(865, 115, 120, 60, "Ch. 1 Enable");
            oscilloscope_fl_light_button_channel_1_enable->callback((Fl_Callback*)cb_oscilloscope_fl_light_button_channel_1_enable);
            oscilloscope_fl_light_button_channel_1_enable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
          } // Fl_Light_Button* oscilloscope_fl_light_button_channel_1_enable
          { oscilloscope_fl_input_choice_channel_1_volts_per_division = new Fl_Input_Choice(865, 215, 120, 30, "Volts per Division");
            oscilloscope_fl_input_choice_channel_1_volts_per_division->callback((Fl_Callback*)cb_oscilloscope_fl_input_choice_channel_1_volts_per_division);
            oscilloscope_fl_input_choice_channel_1_volts_per_division->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_channel_1_volts_per_division->menu(menu_oscilloscope_fl_input_choice_channel_1_volts_per_division);
            oscilloscope_fl_input_choice_channel_1_volts_per_division->value (LABSOFT_OSCILLOSCOPE_CHANNEL_1_VOLTS_PER_DIVISION);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_channel_1_volts_per_division
          { oscilloscope_fl_input_choice_channel_1_vertical_offset = new Fl_Input_Choice(865, 285, 120, 30, "Vertical Offset");
            oscilloscope_fl_input_choice_channel_1_vertical_offset->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_channel_1_vertical_offset->menu(menu_oscilloscope_fl_input_choice_channel_1_vertical_offset);
            oscilloscope_fl_input_choice_channel_1_vertical_offset->value (LABSOFT_OSCILLOSCOPE_CHANNEL_1_Y_OFFSET);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_channel_1_vertical_offset
          oscilloscope_fl_group_vertical_channel_1->end();
        } // Fl_Group* oscilloscope_fl_group_vertical_channel_1
        { oscilloscope_fl_group_vertical_channel_2 = new Fl_Group(0, 0, 1366, 768);
          { Fl_Box* o = new Fl_Box(1015, 95, 160, 240, "Channel 2");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { oscilloscope_fl_light_button_channel_2_enable = new Fl_Light_Button(1035, 115, 120, 60, "Ch. 2 Enable");
            oscilloscope_fl_light_button_channel_2_enable->callback((Fl_Callback*)cb_oscilloscope_fl_light_button_channel_2_enable);
            oscilloscope_fl_light_button_channel_2_enable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
          } // Fl_Light_Button* oscilloscope_fl_light_button_channel_2_enable
          { oscilloscope_fl_input_choice_channel_2_volts_per_division = new Fl_Input_Choice(1035, 215, 120, 30, "Volts per Division");
            oscilloscope_fl_input_choice_channel_2_volts_per_division->callback((Fl_Callback*)cb_oscilloscope_fl_input_choice_channel_2_volts_per_division);
            oscilloscope_fl_input_choice_channel_2_volts_per_division->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_channel_2_volts_per_division->menu(menu_oscilloscope_fl_input_choice_channel_2_volts_per_division);
            oscilloscope_fl_input_choice_channel_2_volts_per_division->value (LABSOFT_OSCILLOSCOPE_CHANNEL_2_VOLTS_PER_DIVISION);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_channel_2_volts_per_division
          { oscilloscope_fl_input_choice_channel_2_vertical_offset = new Fl_Input_Choice(1035, 285, 120, 30, "Vertical Offset");
            oscilloscope_fl_input_choice_channel_2_vertical_offset->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_channel_2_vertical_offset->menu(menu_oscilloscope_fl_input_choice_channel_2_vertical_offset);
            oscilloscope_fl_input_choice_channel_2_vertical_offset->value (LABSOFT_OSCILLOSCOPE_CHANNEL_2_Y_OFFSET);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_channel_2_vertical_offset
          oscilloscope_fl_group_vertical_channel_2->end();
        } // Fl_Group* oscilloscope_fl_group_vertical_channel_2
        { oscilloscope_fl_group_horizontal = new Fl_Group(0, 0, 1366, 768);
          { Fl_Box* o = new Fl_Box(845, 360, 160, 240, "Horizontal");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { oscilloscope_fl_input_choice_time_per_division = new Fl_Input_Choice(865, 400, 120, 30, "Time per Division");
            oscilloscope_fl_input_choice_time_per_division->callback((Fl_Callback*)cb_oscilloscope_fl_input_choice_time_per_division);
            oscilloscope_fl_input_choice_time_per_division->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_time_per_division->menu(menu_oscilloscope_fl_input_choice_time_per_division);
            oscilloscope_fl_input_choice_time_per_division->value (LABSOFT_OSCILLOSCOPE_TIME_PER_DIVISION);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_time_per_division
          { oscilloscope_fl_input_choice_horizontal_offset = new Fl_Input_Choice(865, 465, 120, 30, "Horizontal Offset");
            oscilloscope_fl_input_choice_horizontal_offset->callback((Fl_Callback*)cb_oscilloscope_fl_input_choice_horizontal_offset);
            oscilloscope_fl_input_choice_horizontal_offset->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_horizontal_offset->menu(menu_oscilloscope_fl_input_choice_horizontal_offset);
            oscilloscope_fl_input_choice_horizontal_offset->value (LABSOFT_OSCILLOSCOPE_X_OFFSET);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_horizontal_offset
          { new Fl_Button(865, 520, 120, 60, "Menu");
          } // Fl_Button* o
          oscilloscope_fl_group_horizontal->end();
        } // Fl_Group* oscilloscope_fl_group_horizontal
        { oscilloscope_fl_group_trigger = new Fl_Group(0, 0, 1366, 768);
          { Fl_Box* o = new Fl_Box(1015, 360, 160, 240, "Trigger");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { oscilloscope_fl_input_choice_trigger_level = new Fl_Input_Choice(1035, 400, 120, 30, "Level");
            oscilloscope_fl_input_choice_trigger_level->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_trigger_level->value (LABSOFT_OSCILLOSCOPE_TRIGGER_LEVEL);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_trigger_level
          { new Fl_Button(1035, 445, 120, 60, "Auto");
          } // Fl_Button* o
          { new Fl_Button(1035, 520, 120, 60, "Menu");
          } // Fl_Button* o
          oscilloscope_fl_group_trigger->end();
        } // Fl_Group* oscilloscope_fl_group_trigger
        { oscilloscope_fl_group_display = new Fl_Group(0, 0, 1366, 768);
          oscilloscope_fl_group_display->labeltype(FL_NO_LABEL);
          { Fl_Box* o = new Fl_Box(1185, 360, 160, 240, "Display");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { oscilloscope_fl_input_choice_display_mode = new Fl_Input_Choice(1205, 400, 120, 30, "Mode");
            oscilloscope_fl_input_choice_display_mode->align(Fl_Align(FL_ALIGN_TOP));
            oscilloscope_fl_input_choice_display_mode->menu(menu_oscilloscope_fl_input_choice_display_mode);
            oscilloscope_fl_input_choice_display_mode->value (LABSOFT_OSCILLOSCOPE_DISPLAY_MODE);
          } // Fl_Input_Choice* oscilloscope_fl_input_choice_display_mode
          { new Fl_Button(1205, 445, 120, 60, "Auto");
          } // Fl_Button* o
          { new Fl_Button(1205, 520, 120, 60, "Menu");
          } // Fl_Button* o
          oscilloscope_fl_group_display->end();
        } // Fl_Group* oscilloscope_fl_group_display
        { Fl_Light_Button* o = new Fl_Light_Button(1076, 658, 240, 60, "DEBUG:");
          o->labelsize(11);
          o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Voltmeter");
        o->hide();
        { voltmeter_fl_output_value = new Fl_Output(323, 245, 320, 120);
          voltmeter_fl_output_value->textsize(94);
          voltmeter_fl_output_value->value ("0.000");
        } // Fl_Output* voltmeter_fl_output_value
        { voltmeter_fl_choice_unit = new Fl_Choice(723, 245, 320, 120);
          voltmeter_fl_choice_unit->down_box(FL_BORDER_BOX);
          voltmeter_fl_choice_unit->textsize(100);
          voltmeter_fl_choice_unit->callback((Fl_Callback*)cb_voltmeter_fl_choice_unit);
          voltmeter_fl_choice_unit->menu(menu_voltmeter_fl_choice_unit);
          voltmeter_fl_choice_unit->value (LABSOFT_VOLTMETER_UNIT);
        } // Fl_Choice* voltmeter_fl_choice_unit
        { voltmeter_fl_light_button_run_stop = new Fl_Light_Button(383, 400, 600, 60, "Run");
          voltmeter_fl_light_button_run_stop->selection_color((Fl_Color)79);
          voltmeter_fl_light_button_run_stop->labelsize(24);
          voltmeter_fl_light_button_run_stop->callback((Fl_Callback*)cb_voltmeter_fl_light_button_run_stop);
          voltmeter_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* voltmeter_fl_light_button_run_stop
        { voltmeter_fl_light_button_generate_random_values = new Fl_Light_Button(1076, 658, 240, 60, "DEBUG: Generate Random Values");
          voltmeter_fl_light_button_generate_random_values->labelsize(11);
          voltmeter_fl_light_button_generate_random_values->callback((Fl_Callback*)cb_voltmeter_fl_light_button_generate_random_values);
          voltmeter_fl_light_button_generate_random_values->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* voltmeter_fl_light_button_generate_random_values
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Ammeter");
        o->hide();
        { ammeter_fl_output_value = new Fl_Output(323, 245, 320, 120);
          ammeter_fl_output_value->textsize(94);
          ammeter_fl_output_value->value ("0.000");
        } // Fl_Output* ammeter_fl_output_value
        { ammeter_fl_choice_unit = new Fl_Choice(723, 245, 320, 120);
          ammeter_fl_choice_unit->down_box(FL_BORDER_BOX);
          ammeter_fl_choice_unit->textsize(100);
          ammeter_fl_choice_unit->callback((Fl_Callback*)cb_ammeter_fl_choice_unit);
          ammeter_fl_choice_unit->menu(menu_ammeter_fl_choice_unit);
          ammeter_fl_choice_unit->value (LABSOFT_AMMETER_UNIT);
        } // Fl_Choice* ammeter_fl_choice_unit
        { ammeter_fl_light_button_run_stop = new Fl_Light_Button(383, 400, 600, 60, "Stop");
          ammeter_fl_light_button_run_stop->selection_color((Fl_Color)79);
          ammeter_fl_light_button_run_stop->labelsize(24);
          ammeter_fl_light_button_run_stop->callback((Fl_Callback*)cb_ammeter_fl_light_button_run_stop);
          ammeter_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* ammeter_fl_light_button_run_stop
        { ammeter_fl_light_button_generate_random_values = new Fl_Light_Button(1076, 658, 240, 60, "DEBUG: Generate Random Values");
          ammeter_fl_light_button_generate_random_values->labelsize(11);
          ammeter_fl_light_button_generate_random_values->callback((Fl_Callback*)cb_ammeter_fl_light_button_generate_random_values);
          ammeter_fl_light_button_generate_random_values->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* ammeter_fl_light_button_generate_random_values
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Ohmmeter");
        o->hide();
        { ohmmeter_fl_output_value = new Fl_Output(323, 245, 320, 120);
          ohmmeter_fl_output_value->textsize(94);
          ohmmeter_fl_output_value->value ("0.000");
        } // Fl_Output* ohmmeter_fl_output_value
        { ohmmeter_fl_choice_unit = new Fl_Choice(723, 245, 320, 120);
          ohmmeter_fl_choice_unit->down_box(FL_BORDER_BOX);
          ohmmeter_fl_choice_unit->textsize(100);
          ohmmeter_fl_choice_unit->callback((Fl_Callback*)cb_ohmmeter_fl_choice_unit);
          ohmmeter_fl_choice_unit->menu(menu_ohmmeter_fl_choice_unit);
          ohmmeter_fl_choice_unit->value (LABSOFT_OHMMETER_UNIT);
        } // Fl_Choice* ohmmeter_fl_choice_unit
        { ohmmeter_fl_light_button_run_stop = new Fl_Light_Button(383, 400, 600, 60, "Stopped");
          ohmmeter_fl_light_button_run_stop->selection_color((Fl_Color)79);
          ohmmeter_fl_light_button_run_stop->labelsize(24);
          ohmmeter_fl_light_button_run_stop->callback((Fl_Callback*)cb_ohmmeter_fl_light_button_run_stop);
          ohmmeter_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* ohmmeter_fl_light_button_run_stop
        { ohmmeter_fl_light_button_generate_random_values = new Fl_Light_Button(1076, 658, 240, 60, "DEBUG: Generate Random Values");
          ohmmeter_fl_light_button_generate_random_values->labelsize(11);
          ohmmeter_fl_light_button_generate_random_values->callback((Fl_Callback*)cb_ohmmeter_fl_light_button_generate_random_values);
          ohmmeter_fl_light_button_generate_random_values->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* ohmmeter_fl_light_button_generate_random_values
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Function Generator");
        o->hide();
        { function_generator_fl_light_button_run_stop = new Fl_Light_Button(1205, 80, 120, 60, "Run");
          function_generator_fl_light_button_run_stop->callback((Fl_Callback*)cb_function_generator_fl_light_button_run_stop);
          function_generator_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* function_generator_fl_light_button_run_stop
        { function_generator_labsoft_oscilloscope_display_group_display = new LABSoft_Oscilloscope_Display_Group(24, 60, 800, 660);
          function_generator_labsoft_oscilloscope_display_group_display->box(FL_FLAT_BOX);
          function_generator_labsoft_oscilloscope_display_group_display->color(FL_FOREGROUND_COLOR);
          function_generator_labsoft_oscilloscope_display_group_display->selection_color(FL_BACKGROUND_COLOR);
          function_generator_labsoft_oscilloscope_display_group_display->labeltype(FL_NORMAL_LABEL);
          function_generator_labsoft_oscilloscope_display_group_display->labelfont(0);
          function_generator_labsoft_oscilloscope_display_group_display->labelsize(14);
          function_generator_labsoft_oscilloscope_display_group_display->labelcolor(FL_FOREGROUND_COLOR);
          function_generator_labsoft_oscilloscope_display_group_display->align(Fl_Align(FL_ALIGN_TOP));
          function_generator_labsoft_oscilloscope_display_group_display->when(FL_WHEN_RELEASE);
          { Fl_Box* o = new Fl_Box(64, 120, 720, 540);
            o->box(FL_FLAT_BOX);
            o->color((Fl_Color)79);
            o->selection_color(FL_YELLOW);
            o->hide();
            o->deactivate();
          } // Fl_Box* o
          function_generator_labsoft_oscilloscope_display_group_display->end();
        } // LABSoft_Oscilloscope_Display_Group* function_generator_labsoft_oscilloscope_display_group_display
        { function_generator_fl_group_horizontal = new Fl_Group(0, 0, 1366, 768);
          function_generator_fl_group_horizontal->hide();
          function_generator_fl_group_horizontal->deactivate();
          { Fl_Box* o = new Fl_Box(1110, 542, 200, 150, "Horizontal");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { function_generator_fl_input_choice_horizontal_position = new Fl_Input_Choice(1135, 575, 150, 25, "Position");
            function_generator_fl_input_choice_horizontal_position->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_horizontal_position->menu(menu_function_generator_fl_input_choice_horizontal_position);
            function_generator_fl_input_choice_horizontal_position->value (LABSOFT_FUNCTION_GENERATOR_HORIZONTAL_POSITION);
          } // Fl_Input_Choice* function_generator_fl_input_choice_horizontal_position
          { function_generator_fl_input_choice_time_per_division = new Fl_Input_Choice(1135, 638, 150, 25, "Time per Division");
            function_generator_fl_input_choice_time_per_division->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_time_per_division->when(FL_WHEN_CHANGED);
            function_generator_fl_input_choice_time_per_division->menu(menu_function_generator_fl_input_choice_time_per_division);
            function_generator_fl_input_choice_time_per_division->value (LABSOFT_FUNCTION_GENERATOR_TIME_PER_DIVISION);
          } // Fl_Input_Choice* function_generator_fl_input_choice_time_per_division
          function_generator_fl_group_horizontal->end();
        } // Fl_Group* function_generator_fl_group_horizontal
        { function_generator_fl_group_vertical = new Fl_Group(0, 0, 1366, 768);
          function_generator_fl_group_vertical->hide();
          function_generator_fl_group_vertical->deactivate();
          { Fl_Box* o = new Fl_Box(1110, 347, 200, 150, "Vertical");
            o->box(FL_ROUNDED_BOX);
            o->align(Fl_Align(FL_ALIGN_TOP));
          } // Fl_Box* o
          { function_generator_fl_input_choice_vertical_offset = new Fl_Input_Choice(1135, 380, 150, 25, "Offset");
            function_generator_fl_input_choice_vertical_offset->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_vertical_offset->menu(menu_function_generator_fl_input_choice_vertical_offset);
            function_generator_fl_input_choice_vertical_offset->value (LABSOFT_FUNCTION_GENERATOR_VERTICAL_OFFSET);
          } // Fl_Input_Choice* function_generator_fl_input_choice_vertical_offset
          { function_generator_fl_input_choice_volts_per_division = new Fl_Input_Choice(1135, 443, 150, 25, "Volts per Division");
            function_generator_fl_input_choice_volts_per_division->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_volts_per_division->menu(menu_function_generator_fl_input_choice_volts_per_division);
            function_generator_fl_input_choice_volts_per_division->value ("1 V/div");
          } // Fl_Input_Choice* function_generator_fl_input_choice_volts_per_division
          function_generator_fl_group_vertical->end();
        } // Fl_Group* function_generator_fl_group_vertical
        { function_generator_fl_group_parameters = new Fl_Group(0, 0, 1366, 768);
          { function_generator_fl_input_choice_wave_type = new Fl_Input_Choice(880, 90, 120, 40, "Wave Type");
            function_generator_fl_input_choice_wave_type->callback((Fl_Callback*)cb_function_generator_fl_input_choice_wave_type);
            function_generator_fl_input_choice_wave_type->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_wave_type->menu(menu_function_generator_fl_input_choice_wave_type);
            function_generator_fl_input_choice_wave_type->value (LABSOFT_FUNCTION_GENERATOR_WAVE_TYPE);
          } // Fl_Input_Choice* function_generator_fl_input_choice_wave_type
          { function_generator_fl_input_choice_frequency = new Fl_Input_Choice(1030, 90, 120, 40, "Frequency");
            function_generator_fl_input_choice_frequency->callback((Fl_Callback*)cb_function_generator_fl_input_choice_frequency);
            function_generator_fl_input_choice_frequency->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_frequency->menu(menu_function_generator_fl_input_choice_frequency);
            function_generator_fl_input_choice_frequency->value (LABSOFT_FUNCTION_GENERATOR_FREQUENCY);
          } // Fl_Input_Choice* function_generator_fl_input_choice_frequency
          { function_generator_fl_input_choice_period = new Fl_Input_Choice(880, 200, 120, 40, "Period");
            function_generator_fl_input_choice_period->callback((Fl_Callback*)cb_function_generator_fl_input_choice_period);
            function_generator_fl_input_choice_period->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_period->deactivate();
            function_generator_fl_input_choice_period->menu(menu_function_generator_fl_input_choice_period);
            function_generator_fl_input_choice_period->value (LABSOFT_FUNCTION_GENERATOR_PERIOD);
          } // Fl_Input_Choice* function_generator_fl_input_choice_period
          { function_generator_fl_input_choice_amplitude = new Fl_Input_Choice(1030, 200, 120, 40, "Amplitude");
            function_generator_fl_input_choice_amplitude->callback((Fl_Callback*)cb_function_generator_fl_input_choice_amplitude);
            function_generator_fl_input_choice_amplitude->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_amplitude->menu(menu_function_generator_fl_input_choice_amplitude);
            function_generator_fl_input_choice_amplitude->value (LABSOFT_FUNCTION_GENERATOR_AMPLITUDE);
          } // Fl_Input_Choice* function_generator_fl_input_choice_amplitude
          { function_generator_fl_input_choice_y_offset = new Fl_Input_Choice(880, 300, 120, 40, "Vertical Offset");
            function_generator_fl_input_choice_y_offset->callback((Fl_Callback*)cb_function_generator_fl_input_choice_y_offset);
            function_generator_fl_input_choice_y_offset->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_y_offset->menu(menu_function_generator_fl_input_choice_y_offset);
            function_generator_fl_input_choice_y_offset->value (LABSOFT_FUNCTION_GENERATOR_Y_OFFSET);
          } // Fl_Input_Choice* function_generator_fl_input_choice_y_offset
          { function_generator_fl_input_choice_duty_cycle = new Fl_Input_Choice(1030, 300, 120, 40, "Duty Cycle");
            function_generator_fl_input_choice_duty_cycle->callback((Fl_Callback*)cb_function_generator_fl_input_choice_duty_cycle);
            function_generator_fl_input_choice_duty_cycle->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_duty_cycle->deactivate();
            function_generator_fl_input_choice_duty_cycle->menu(menu_function_generator_fl_input_choice_duty_cycle);
            function_generator_fl_input_choice_duty_cycle->value (LABSOFT_FUNCTION_GENERATOR_DUTY_CYCLE);
          } // Fl_Input_Choice* function_generator_fl_input_choice_duty_cycle
          { function_generator_fl_input_choice_phase = new Fl_Input_Choice(880, 400, 120, 40, "Phase");
            function_generator_fl_input_choice_phase->callback((Fl_Callback*)cb_function_generator_fl_input_choice_phase);
            function_generator_fl_input_choice_phase->align(Fl_Align(FL_ALIGN_TOP));
            function_generator_fl_input_choice_phase->menu(menu_function_generator_fl_input_choice_phase);
            function_generator_fl_input_choice_phase->value (LABSOFT_FUNCTION_GENERATOR_PHASE);
          } // Fl_Input_Choice* function_generator_fl_input_choice_phase
          function_generator_fl_group_parameters->end();
        } // Fl_Group* function_generator_fl_group_parameters
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Logic Analyzer");
        o->hide();
        { logic_analyzer_fl_light_button_run_stop = new Fl_Light_Button(1205, 80, 120, 60, "Run");
          logic_analyzer_fl_light_button_run_stop->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* logic_analyzer_fl_light_button_run_stop
        { new Fl_Button(1205, 160, 120, 60, "Single");
        } // Fl_Button* o
        { logic_analyzer_oscilloscope_display_group_display = new LABSoft_Oscilloscope_Display_Group(24, 60, 800, 660);
          logic_analyzer_oscilloscope_display_group_display->box(FL_FLAT_BOX);
          logic_analyzer_oscilloscope_display_group_display->color(FL_FOREGROUND_COLOR);
          logic_analyzer_oscilloscope_display_group_display->selection_color(FL_BACKGROUND_COLOR);
          logic_analyzer_oscilloscope_display_group_display->labeltype(FL_NORMAL_LABEL);
          logic_analyzer_oscilloscope_display_group_display->labelfont(0);
          logic_analyzer_oscilloscope_display_group_display->labelsize(14);
          logic_analyzer_oscilloscope_display_group_display->labelcolor(FL_FOREGROUND_COLOR);
          logic_analyzer_oscilloscope_display_group_display->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_oscilloscope_display_group_display->when(FL_WHEN_RELEASE);
          { Fl_Box* o = new Fl_Box(79, 135, 720, 540);
            o->box(FL_FLAT_BOX);
            o->color((Fl_Color)79);
            o->selection_color(FL_YELLOW);
            o->hide();
            o->deactivate();
          } // Fl_Box* o
          logic_analyzer_oscilloscope_display_group_display->end();
        } // LABSoft_Oscilloscope_Display_Group* logic_analyzer_oscilloscope_display_group_display
        { logic_analyzer_fl_input_choice_memory_depth = new Fl_Input_Choice(1205, 260, 120, 30, "Memory Depth");
          logic_analyzer_fl_input_choice_memory_depth->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_fl_input_choice_memory_depth->menu(menu_logic_analyzer_fl_input_choice_memory_depth);
        } // Fl_Input_Choice* logic_analyzer_fl_input_choice_memory_depth
        { logic_analyzer_fl_input_choice_sample_rate = new Fl_Input_Choice(1205, 330, 120, 30, "Sample_Rate");
          logic_analyzer_fl_input_choice_sample_rate->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_fl_input_choice_sample_rate->menu(menu_logic_analyzer_fl_input_choice_sample_rate);
        } // Fl_Input_Choice* logic_analyzer_fl_input_choice_sample_rate
        { logic_analyzer_fl_input_choice_samples_per_division = new Fl_Input_Choice(1205, 400, 120, 30, "Samples per Division");
          logic_analyzer_fl_input_choice_samples_per_division->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_fl_input_choice_samples_per_division->menu(menu_logic_analyzer_fl_input_choice_samples_per_division);
        } // Fl_Input_Choice* logic_analyzer_fl_input_choice_samples_per_division
        { logic_analyzer_fl_input_choice_time_per_division = new Fl_Input_Choice(1205, 470, 120, 30, "Time per DIvision");
          logic_analyzer_fl_input_choice_time_per_division->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_fl_input_choice_time_per_division->menu(menu_logic_analyzer_fl_input_choice_time_per_division);
        } // Fl_Input_Choice* logic_analyzer_fl_input_choice_time_per_division
        { logic_analyzer_fl_input_choice_x_offset = new Fl_Input_Choice(1205, 540, 120, 30, "Horizontal Offset");
          logic_analyzer_fl_input_choice_x_offset->align(Fl_Align(FL_ALIGN_TOP));
          logic_analyzer_fl_input_choice_x_offset->menu(menu_logic_analyzer_fl_input_choice_x_offset);
        } // Fl_Input_Choice* logic_analyzer_fl_input_choice_x_offset
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Power Supply");
        o->hide();
        { power_supply_fl_light_button_positive_12_volts_enable_disable = new Fl_Light_Button(273, 240, 240, 120, "+12V");
          power_supply_fl_light_button_positive_12_volts_enable_disable->selection_color((Fl_Color)79);
          power_supply_fl_light_button_positive_12_volts_enable_disable->labelsize(48);
          power_supply_fl_light_button_positive_12_volts_enable_disable->callback((Fl_Callback*)cb_power_supply_fl_light_button_positive_12_volts_enable_disable);
          power_supply_fl_light_button_positive_12_volts_enable_disable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* power_supply_fl_light_button_positive_12_volts_enable_disable
        { power_supply_fl_light_button_negative_12_volts_enable_disable = new Fl_Light_Button(563, 240, 240, 120, "-12V");
          power_supply_fl_light_button_negative_12_volts_enable_disable->selection_color((Fl_Color)79);
          power_supply_fl_light_button_negative_12_volts_enable_disable->labelsize(48);
          power_supply_fl_light_button_negative_12_volts_enable_disable->callback((Fl_Callback*)cb_power_supply_fl_light_button_negative_12_volts_enable_disable);
          power_supply_fl_light_button_negative_12_volts_enable_disable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* power_supply_fl_light_button_negative_12_volts_enable_disable
        { power_supply_fl_light_button_positive_5_volts_enable_disable = new Fl_Light_Button(853, 240, 240, 120, "+5V");
          power_supply_fl_light_button_positive_5_volts_enable_disable->selection_color((Fl_Color)79);
          power_supply_fl_light_button_positive_5_volts_enable_disable->labelsize(48);
          power_supply_fl_light_button_positive_5_volts_enable_disable->callback((Fl_Callback*)cb_power_supply_fl_light_button_positive_5_volts_enable_disable);
          power_supply_fl_light_button_positive_5_volts_enable_disable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* power_supply_fl_light_button_positive_5_volts_enable_disable
        { power_supply_fl_light_button_master_enable_disable = new Fl_Light_Button(383, 400, 600, 60, "Master Enable");
          power_supply_fl_light_button_master_enable_disable->selection_color((Fl_Color)79);
          power_supply_fl_light_button_master_enable_disable->labelsize(24);
          power_supply_fl_light_button_master_enable_disable->callback((Fl_Callback*)cb_power_supply_fl_light_button_master_enable_disable);
          power_supply_fl_light_button_master_enable_disable->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
        } // Fl_Light_Button* power_supply_fl_light_button_master_enable_disable
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Circuit Checker");
        o->hide();
        { circuit_checker_fl_button_choose_circuit_checker_file = new Fl_Button(203, 180, 300, 120, "Choose Circuit   Checker File");
          circuit_checker_fl_button_choose_circuit_checker_file->labelsize(24);
          circuit_checker_fl_button_choose_circuit_checker_file->callback((Fl_Callback*)cb_circuit_checker_fl_button_choose_circuit_checker_file);
          circuit_checker_fl_button_choose_circuit_checker_file->align(Fl_Align(FL_ALIGN_WRAP));
        } // Fl_Button* circuit_checker_fl_button_choose_circuit_checker_file
        { circuit_checker_fl_button_start_circuit_checking = new Fl_Button(533, 180, 300, 120, "Start Circuit Checking");
          circuit_checker_fl_button_start_circuit_checking->labelsize(24);
          circuit_checker_fl_button_start_circuit_checking->callback((Fl_Callback*)cb_circuit_checker_fl_button_start_circuit_checking);
        } // Fl_Button* circuit_checker_fl_button_start_circuit_checking
        { circuit_checker_fl_output_selected_circuit_checker_file = new Fl_Output(863, 160, 300, 60, "Selected Circuit Checker File");
          circuit_checker_fl_output_selected_circuit_checker_file->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Output* circuit_checker_fl_output_selected_circuit_checker_file
        { circuit_checker_fl_output_similarity_score = new Fl_Output(863, 250, 300, 60, "Similarity Score");
          circuit_checker_fl_output_similarity_score->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        } // Fl_Output* circuit_checker_fl_output_similarity_score
        { circuit_checker_fl_text_display_logger = new Fl_Text_Display(203, 340, 960, 240);
        } // Fl_Text_Display* circuit_checker_fl_text_display_logger
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 35, 1366, 768, "Settings");
        o->hide();
        { Fl_Group* o = new Fl_Group(35, 70, 300, 120, "Settings");
          o->labelsize(48);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { alignment_guides = new Fl_Group(0, 0, 1366, 768);
      alignment_guides->hide();
      alignment_guides->deactivate();
      { inner_height = new Fl_Box(0, 35, 1366, 366);
        inner_height->box(FL_UP_FRAME);
        inner_height->color(FL_RED);
      } // Fl_Box* inner_height
      { outer_height = new Fl_Box(0, 0, 1366, 384);
        outer_height->box(FL_DOWN_FRAME);
        outer_height->color(FL_YELLOW);
      } // Fl_Box* outer_height
      { inner_height_crosswise = new Fl_Box(0, 0, 683, 768);
        inner_height_crosswise->box(FL_UP_FRAME);
        inner_height_crosswise->color(FL_RED);
      } // Fl_Box* inner_height_crosswise
      alignment_guides->end();
    } // Fl_Group* alignment_guides
    main_fl_window->end();
  } // Fl_Double_Window* main_fl_window
  printf("DEBUG: LABSoft_GUI Constructor OK\n");
}
