// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef LABSoft_GUI_Logic_Analyzer_Channel_Button_h
#define LABSoft_GUI_Logic_Analyzer_Channel_Button_h
#include <FL/Fl.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Menu_Button.H>

class LABSoft_GUI_Logic_Analyzer_Channel_Button : public Fl_Group {
public:
  LABSoft_GUI_Logic_Analyzer_Channel_Button(int X, int Y, int W, int H, const char *L = 0);
  Fl_Input *fl_input_name;
  Fl_Output *fl_output_pin;
  Fl_Menu_Button *fl_menu_button_trigger;
  static Fl_Menu_Item menu_fl_menu_button_trigger[];
};
#endif
