// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "LABSoft_GUI_Logic_Analyzer_Channel_Button.h"

Fl_Menu_Item LABSoft_GUI_Logic_Analyzer_Channel_Button::menu_fl_menu_button_trigger[] = {
 {"X - Ignore", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"0 - Low", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"1 - High", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"^ - Rise", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"v - Fall", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"| - Edge", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
LABSoft_GUI_Logic_Analyzer_Channel_Button::LABSoft_GUI_Logic_Analyzer_Channel_Button(int X, int Y, int W, int H, const char *L)
  : Fl_Group(X, Y, W, H, L) {
this->box(FL_GTK_UP_BOX);
this->color((Fl_Color)53);
{ fl_input_name = new Fl_Input(0, 0, 80, 60);
  fl_input_name->box(FL_THIN_DOWN_BOX);
  fl_input_name->color(FL_LIGHT2);
} // Fl_Input* fl_input_name
{ fl_output_pin = new Fl_Output(80, 0, 60, 60);
  fl_output_pin->box(FL_THIN_DOWN_BOX);
  fl_output_pin->color(FL_YELLOW);
} // Fl_Output* fl_output_pin
{ fl_menu_button_trigger = new Fl_Menu_Button(140, 0, 40, 60, "X");
  fl_menu_button_trigger->box(FL_GTK_UP_BOX);
  fl_menu_button_trigger->color((Fl_Color)53);
  fl_menu_button_trigger->menu(menu_fl_menu_button_trigger);
} // Fl_Menu_Button* fl_menu_button_trigger
end();
}
